### ISSUE TITLE
read me file unclear

### ISSUE THREAD

**Issue by scottl86** [ajilderda/alfred-harvest-v2#11]
I apologize for the simple question, new to Alfred and GitHub

I installed node.js, created a Personal Access Token in Harvest, next steps says "Type `hvs` and press <kbd>enter</kbd>"

Where? Alfred? It just gives me the default Google search. Am I supposed to install the GitHub files into Alfred first? How? 

Thank you in advance for your help.

**Comment by ajilderda** [comment]
Hi Scott, no worries! 

Since `hvs` is just giving you a Google search it seems you haven't installed the workflow, am I right? To do so download [this file](https://github.com/ajilderda/alfred-harvest-v2/releases/download/1.1.3/alfred-harvest-v2.alfredworkflow) and open it in Alfred. After doing so `hvs` should ask you for your Harvest API token.

**Comment by ajilderda** [comment]
@scottl86 Closing this. Let me know if your issue hasn't been resolved.
